name: Run Python Script Daily and on Push/PR

on:
  schedule:
    # Run at 8 AM UTC every day
    - cron: '0 8 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python model_miner.py

    # Configure git user (necessary for committing changes)
    - name: Configure git user
      run: |
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'

    # Add generated files to the git index (you may need to modify the path to the files)
    - name: Add files
      run: git add data/feature-extraction/*

    # Commit the changes
    - name: Commit files
      run: git commit -m "Add generated model files"

    # Push the changes back to the repository
    - name: Push changes
      run: git push