name: Run Python Script Daily and on Push/PR

on:
  schedule:
    # Run at 8 AM UTC every day
    - cron: '0 8 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python model_miner.py

      # Configure git user (necessary for committing changes)
      - name: Configure git user
        run: |
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'

      # Add generated files to the git index
      - name: Add files
        run: git add data/feature-extraction/*

      # Commit the changes
      - name: Commit files
        run: git commit -m "Add generated model files" || echo "No changes to commit"

      # Push the changes back to the repository
      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  deploy:
    needs: run-script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
